/** Portal rows for the careers helpers' tests: a full record, with only what a test needs changed. */
import type { Gig, Job, JobCompany } from "../../../../src/lib/portal/types";

export const company = (overrides: Partial<JobCompany> = {}): JobCompany => ({
  id: "c1",
  companyCode: "ACME",
  slug: "acme",
  name: "Acme",
  logo: "",
  tagline: "",
  description: "",
  culture: "",
  website: "",
  founded: "",
  employees: "",
  industry: "",
  headquarters: "",
  benefits: [],
  socialLinks: { linkedin: "", twitter: "", facebook: "", instagram: "" },
  brandColor: "",
  secondaryColor: "",
  ...overrides,
});

export const job = (overrides: Partial<Job> = {}): Job => ({
  id: "j1",
  jobCode: "JOB-1",
  companySlug: "acme",
  title: "Engineer",
  category: "Engineering",
  skillSet: [],
  shortJobDescription: "Builds things",
  jobDescription: "",
  jobResponsibilities: "",
  requirements: [],
  niceToHave: [],
  benefits: [],
  location: "Pune, India",
  jobType: "Full Time",
  experienceLevel: "",
  workMode: "On-site",
  salaryRange: "",
  jobPostDate: "2026-09-01",
  applicationDeadline: null,
  isFeatured: false,
  ...overrides,
});

export const gig = (overrides: Partial<Gig> = {}): Gig => ({
  id: "g1",
  gigCode: "GIG-1",
  title: "Logo design",
  category: "Design",
  shortDescription: "A new logo",
  fullDescription: "",
  deliverables: [],
  requirements: [],
  tags: [],
  budget: "",
  duration: "",
  status: "open",
  applicationType: "email",
  applicationContact: "jobs@example.com",
  postedDate: "2026-09-01",
  deadline: null,
  isUrgent: false,
  ...overrides,
});
