/**
 * Names, not pictures: a workflow says `icon: 'doctor'` and `accent: 'teal'`, and each screen
 * maps the name to its own icon set and colour tokens. Adding a key here means adding its
 * icon in the app's `components/wa/icons.ts` (the type check fails until you do).
 */
export const ICON_KEYS = [
  // Generic
  'business',
  'chat',
  'calendar',
  'clock',
  'location',
  'phone',
  'mail',
  'document',
  'receipt',
  'payment',
  'ticket',
  'qr',
  'gift',
  'star',
  'offer',
  'support',
  'info',
  'check',
  'warning',
  'person',
  'family',
  'child',
  'group',
  'home',
  'search',
  'link',
  'bell',
  'lock',
  'cart',
  'bag',
  // Healthcare
  'hospital',
  'doctor',
  'stethoscope',
  'lab',
  'vaccine',
  'pill',
  'heart',
  'tooth',
  'eye',
  'bone',
  'brain',
  'baby',
  'report',
  'ambulance',
  // Other industries
  'school',
  'book',
  'bank',
  'card',
  'loan',
  'insurance',
  'car',
  'bike',
  'truck',
  'flight',
  'train',
  'hotel',
  'bed',
  'restaurant',
  'food',
  'coffee',
  'grocery',
  'store',
  'shirt',
  'beauty',
  'spa',
  'fitness',
  'sports',
  'movie',
  'music',
  'event',
  'realestate',
  'key',
  'tools',
  'electricity',
  'water',
  'wifi',
  'mobile',
  'laptop',
  'pet',
  'plant',
  'government',
  'legal',
  'shipping',
  'factory',
  'solar',
] as const;

export type IconKey = (typeof ICON_KEYS)[number];

/** Avatar and illustration tints. Each maps to a light and a dark colour token in the app. */
export const ACCENT_KEYS = [
  'teal',
  'green',
  'blue',
  'indigo',
  'purple',
  'pink',
  'red',
  'orange',
  'amber',
  'cyan',
  'slate',
  'brown',
] as const;

export type AccentKey = (typeof ACCENT_KEYS)[number];
