import {
  invoiceDocument,
  type InvoicePdfData,
} from '../../../../src/modules/finance/invoice.document';
import { buildInvoicePdf, invoiceFilename } from '../../../../src/modules/finance/invoice.pdf';

const LINE = { description: 'Design', quantity: 2, rate: 1000, taxPercent: 18 };

/** A bare invoice: one figure, nothing optional filled in, not under India's GST. */
const bare = (overrides: Partial<InvoicePdfData['invoice']> = {}): InvoicePdfData => ({
  locale: 'en-US',
  indianTaxRules: false,
  company: {
    name: 'Exyconn',
    address: '',
    supportEmail: '',
    gstin: '',
    stateCode: '',
    bankDetails: '',
  },
  client: {
    name: 'Priya',
    company: '',
    email: '',
    taxId: '',
    taxIdLabel: '',
    billingAddress: '',
  },
  invoice: {
    number: 'INV-100',
    currency: 'USD',
    status: 'PARTIALLY_PAID',
    issuedDate: new Date('2026-09-01T00:00:00.000Z'),
    dueDate: new Date('2026-09-30T00:00:00.000Z'),
    lines: [],
    amount: 500,
    amountPaid: 125,
    placeOfSupplyStateCode: '',
    supplierStateCode: '',
    ...overrides,
  },
});

describe('invoiceDocument with nothing optional on file', () => {
  it('prints only the supplier name and the plain parties', () => {
    const document = invoiceDocument(bare());

    expect(document.title).toBe('Invoice');
    expect(document.supplier).toEqual(['Exyconn']);
    expect(document.parties).toEqual([
      { label: 'Billed to', value: 'Priya' },
      { label: 'Issued', value: '2026-09-01' },
      { label: 'Due', value: '2026-09-30' },
      { label: 'Status', value: 'PARTIALLY PAID' },
    ]);
    expect(document.footer).toBe('This invoice is generated by the Exyconn portal.');
  });

  it('has no line table and only the money rows for a single-figure invoice', () => {
    const document = invoiceDocument(bare());

    expect(document.lines).toEqual([]);
    expect(document.totals).toEqual([
      { label: 'Total', value: '$500.00', emphasis: true },
      { label: 'Amount paid', value: '$125.00' },
      { label: 'Balance due', value: '$375.00', emphasis: true },
    ]);
  });

  it('labels a tax number with no known kind as a tax ID', () => {
    const data = bare();
    data.client.taxId = 'DE123456789';

    expect(invoiceDocument(data).parties).toContainEqual({
      label: 'Client tax ID',
      value: 'DE123456789',
    });
  });

  it('formats every cell of a line in the company currency', () => {
    const document = invoiceDocument(bare({ lines: [LINE], amount: 2360 }));

    expect(document.lines).toEqual([
      {
        description: 'Design',
        hsnSac: '',
        quantity: '2',
        rate: '$1,000.00',
        tax: '18%',
        amount: '$2,360.00',
      },
    ]);
    expect(document.totals.slice(0, 2)).toEqual([
      { label: 'Subtotal', value: '$2,000.00' },
      { label: 'Tax', value: '$360.00' },
    ]);
  });
});

describe('invoiceDocument under India GST', () => {
  it('splits the tax into CGST and SGST inside the supplier state', () => {
    const data = bare({
      lines: [LINE],
      amount: 2360,
      placeOfSupplyStateCode: '23',
      supplierStateCode: '23',
    });
    data.indianTaxRules = true;
    data.locale = 'en-IN';
    data.invoice.currency = 'INR';

    const document = invoiceDocument(data);

    expect(document.title).toBe('Tax Invoice');
    expect(document.totals.filter((row) => row.label.endsWith('GST'))).toEqual([
      { label: 'CGST', value: '₹180.00' },
      { label: 'SGST', value: '₹180.00' },
    ]);
    expect(document.parties).toContainEqual({
      label: 'Place of supply',
      value: '23 — Madhya Pradesh',
    });
  });
});

describe('invoiceFilename', () => {
  it('trims stray separators and falls back to "draft" when nothing safe is left', () => {
    expect(invoiceFilename('--INV 9--')).toBe('Invoice-INV-9.pdf');
    expect(invoiceFilename('###')).toBe('Invoice-draft.pdf');
    expect(invoiceFilename('')).toBe('Invoice-draft.pdf');
  });
});

describe('buildInvoicePdf', () => {
  it('renders a complete PDF for a single-figure invoice without bank details', async () => {
    const pdf = await buildInvoicePdf(bare());

    expect(pdf.subarray(0, 4).toString('latin1')).toBe('%PDF');
    expect(pdf.subarray(-6).toString('latin1')).toContain('%%EOF');
  });

  it('renders a longer document when there is a line table to draw', async () => {
    const withoutLines = await buildInvoicePdf(bare());
    const withLines = await buildInvoicePdf(bare({ lines: [LINE, LINE], amount: 4720 }));

    expect(withLines.length).toBeGreaterThan(withoutLines.length);
  });
});
