/**
 * Every English word the chat shows, in one object so it can be translated in one place.
 * The bot name, welcome and offline messages and the FAQs come from the server's config.
 */
export const strings = {
  defaultTitle: "Exyconn",
  frameTitle: "Chat with Exyconn",
  openChat: "Open chat",
  closeChat: "Close chat",
  unread: (count: number) => (count === 1 ? "1 unread message" : `${count} unread messages`),
  online: "Online",
  offline: "Offline",
  todayHours: (start: string, end: string) => `Today ${start}–${end}`,
  closedToday: "Closed today",
  settings: "Chat settings",
  minimise: "Minimise chat",
  sound: "Sound",
  download: "Download conversation",
  endChat: "End chat",
  endTitle: "End this chat?",
  endConfirm: "A copy of the conversation is emailed to you.",
  endConfirmYes: "End chat",
  cancel: "Cancel",
  tabsLabel: "Chat sections",
  tabLive: "Chat with us",
  tabKnowledge: "Knowledge Bot",
  tabFaqs: "FAQs",
  connecting: "Connecting…",
  reconnecting: "Reconnecting…",
  notConnected: "Not connected yet. Try again in a moment.",
  dismiss: "Dismiss",
  signInTitle: "Before we start",
  signInIntro: "We email you a code to confirm it is you, and a copy of the chat when it ends.",
  name: "Name",
  nameHint: "How the team should address you.",
  email: "Email",
  emailHint: "We send a 6-digit code here.",
  phone: "Phone (optional)",
  phoneHint: "Only if you would like a call back.",
  requestCode: "Email me a code",
  privacy: "How we use your details",
  nameRequired: "Enter your name.",
  nameTooLong: "Keep your name shorter.",
  nameLink: "Enter your name without links or email addresses.",
  emailRequired: "Enter your email address.",
  emailInvalid: "Enter a valid email address.",
  phoneInvalid: "Enter a valid phone number.",
  codeTitle: "Check your email",
  codeSentTo: (email: string) => `We emailed a 6-digit code to ${email}.`,
  code: "6-digit code",
  codeHint: "The code expires after a few minutes.",
  codeInvalid: "Enter the 6-digit code from the email.",
  verify: "Verify and start chatting",
  resend: "Resend code",
  resendIn: (seconds: number) => `Resend code in ${seconds}s`,
  changeEmail: "Change email",
  conversation: (section: string) => `${section} conversation`,
  messageLabel: (section: string) => `Message ${section}`,
  placeholderLive: "Write a message…",
  placeholderKnowledge: "Ask about Exyconn…",
  send: "Send message",
  charsLeft: (count: number) => `${count} characters left`,
  attach: "Attach a picture or video",
  removeFile: (name: string) => `Remove ${name}`,
  fileTooBig: (name: string, mb: number) => `${name} is larger than ${mb} MB.`,
  tooManyFiles: "Send at most four files at a time.",
  fileType: (name: string) => `${name} is not a picture or a video.`,
  fileUnreadable: "The file could not be read.",
  record: "Record a voice note",
  recording: "Recording voice note",
  stopSend: "Stop and send voice note",
  cancelRecording: "Cancel recording",
  micDenied:
    "Microphone access is blocked. Allow it in your browser settings to send a voice note.",
  micUnsupported: "This browser cannot record voice notes.",
  micFailed: "The voice note could not be recorded.",
  sending: "Sending…",
  failed: "Not sent",
  retry: "Retry",
  seen: "Seen",
  you: "You",
  bot: "Bot",
  typing: (name: string) => `${name} is typing`,
  chattingWith: (name: string) => `You're chatting with ${name}`,
  ended: "This chat has ended",
  endedHint: "Start a new chat any time — you will not need a new code.",
  newChat: "Start a new chat",
  endsIn: (time: string) => `Chat ends in ${time} without a reply`,
  endsSoon: (minutes: number) =>
    minutes <= 1
      ? "This chat ends in under a minute without a reply."
      : `This chat ends in ${minutes} minutes without a reply.`,
  newMessages: "New messages",
  today: "Today",
  yesterday: "Yesterday",
  knowledgeIntroTitle: (botName: string) => `Hi, I'm ${botName}`,
  knowledgeIntro:
    "Ask me anything about Exyconn — our services, products and how we work. I answer from Exyconn's own pages.",
  tryAsking: "Try asking",
  talkToPerson: "Talk to a person",
  liveIntroTitle: "Talk to our team",
  sources: "Sources",
  suggestions: "Suggested questions",
  helpful: "Helpful",
  notHelpful: "Not helpful",
  thanksFeedback: "Thanks for the feedback",
  searchFaqs: "Search FAQs",
  noFaqMatch: "No answers match your search.",
  noFaqs: "No FAQs yet.",
  stillNeedHelp: "Still need help?",
  chatWithUs: "Chat with us",
  askTheBot: "Ask the Knowledge Bot",
  newMessageFrom: (name: string, body: string) => `New message from ${name}: ${body}`,
  attachmentFrom: (name: string) => `${name} sent an attachment`,
  openAttachment: (name: string) => `Open ${name} in a new tab`,
  transcriptTitle: (reference: string) => `Exyconn chat ${reference}`,
} as const;
