import { useEffect, useMemo, useRef } from 'react';
import { useT } from '@exyconn/i18n';
import { Box } from '@exyconn/shell/components/ui';
import LockIcon from '@mui/icons-material/Lock';
import type { ChatMessage } from '@exyconn/wa-flow';
import { useWaFormat } from '../../../hooks/useWaFormat';
import { useCompact, useReducedMotion, useWaPalette } from '../../../theme/useWa';
import { WA_FONT, WA_RADIUS, WA_SPACE } from '../../../theme/wa.tokens';
import { MessageView } from '../messages/MessageView';
import { DateChip } from './DateChip';
import { relativeDay, timeline } from './timeline';
import { TypingBubble } from './TypingBubble';

interface MessageListProps {
  messages: readonly ChatMessage[];
  typing: boolean;
}

/** The scrolling conversation: notice, date chips, bubbles and "typing…", pinned to the newest. */
export function MessageList({ messages, typing }: Readonly<MessageListProps>) {
  const t = useT();
  const c = useWaPalette();
  const compact = useCompact();
  const reduced = useReducedMotion();
  const format = useWaFormat();
  const scroller = useRef<HTMLDivElement>(null);
  const rows = useMemo(() => timeline(messages), [messages]);

  useEffect(() => {
    const el = scroller.current;
    el?.scrollTo({ top: el.scrollHeight, behavior: reduced ? 'auto' : 'smooth' });
  }, [rows.length, typing, reduced]);

  return (
    <Box
      ref={scroller}
      role="region"
      aria-label={t('Messages')}
      tabIndex={0}
      sx={{
        flex: 1,
        minHeight: 0,
        overflowY: 'auto',
        overflowX: 'hidden',
        px: compact ? WA_SPACE.gutterCompact : WA_SPACE.gutter,
        pb: WA_SPACE.md,
        display: 'flex',
        flexDirection: 'column',
        '&:focus-visible': { outline: 'none' },
      }}
    >
      <Box
        sx={{
          alignSelf: 'center',
          display: 'flex',
          gap: WA_SPACE.xs,
          maxWidth: '90%',
          mt: WA_SPACE.md,
          px: WA_SPACE.md,
          py: WA_SPACE.xs,
          borderRadius: WA_RADIUS.chip,
          bgcolor: c.notice,
          color: c.noticeText,
          fontSize: WA_FONT.small,
          textAlign: 'center',
        }}
      >
        <LockIcon sx={{ fontSize: WA_FONT.title }} />
        <span>
          {t('Messages in this demo are generated by an automation engine and stay on this page.')}
        </span>
      </Box>
      <Box role="log" aria-live="polite" sx={{ display: 'flex', flexDirection: 'column' }}>
        {rows.map((row) => {
          if (row.kind === 'date') {
            const relative = relativeDay(row.dayMs, Date.now());
            return (
              <DateChip key={row.id} label={relative ? t(relative) : format.date(row.dayMs)} />
            );
          }
          return (
            <MessageView
              key={row.id}
              message={row.message}
              tail={row.tail}
              time={format.time(row.message.at)}
            />
          );
        })}
      </Box>
      {typing ? <TypingBubble /> : null}
    </Box>
  );
}
