import { afterEach, describe, expect, it, vi } from 'vitest';
import { screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { DocumentAttachment } from '@exyconn/wa-flow';
import { DocumentDialog } from '../../../../../src/components/wa/chat/DocumentDialog';
import { renderWithProviders } from '../../../test-utils';

const view = vi.hoisted(() => ({ compact: false }));

vi.mock('../../../../../src/theme/useWa', async (importOriginal) => ({
  ...(await importOriginal<object>()),
  useCompact: () => view.compact,
}));

afterEach(() => {
  view.compact = false;
});

const REPORT: DocumentAttachment = {
  fileName: 'blood-report.pdf',
  fileType: 'PDF',
  pages: 2,
  sizeKb: 120,
  preview: {
    title: 'Blood test report',
    subtitle: 'Patient: Asha Nair',
    sections: [
      {
        kind: 'fields',
        heading: 'Patient',
        fields: [
          { label: 'Age', value: '34' },
          { label: 'Sample', value: 'Serum' },
        ],
      },
      {
        kind: 'table',
        heading: 'Results',
        columns: ['Test', 'Value', 'Range'],
        rows: [
          { id: 'hb', cells: ['Haemoglobin', '10.1', '12–16'], flag: 'low' },
          { id: 'glu', cells: ['Glucose', '160', '70–110'], flag: 'high' },
          { id: 'na', cells: ['Sodium', '140', '135–145'] },
        ],
      },
      { kind: 'text', text: 'Please consult your doctor.\nRepeat in 3 months.' },
    ],
    footer: 'Generated by the demo lab',
  },
};

describe('DocumentDialog', () => {
  it('lays out the document like its printed page', async () => {
    renderWithProviders(<DocumentDialog document={REPORT} onClose={vi.fn()} />);
    const dialog = await screen.findByRole('dialog', { name: /blood-report\.pdf/ });
    expect(
      within(dialog).getByRole('heading', { level: 2, name: 'Blood test report' }),
    ).toBeInTheDocument();
    expect(dialog).toHaveTextContent('Patient: Asha Nair');
    expect(within(dialog).getByRole('heading', { level: 3, name: 'Patient' })).toBeInTheDocument();
    expect(within(dialog).getByText('Age')).toBeInTheDocument();
    expect(within(dialog).getByText('Serum')).toBeInTheDocument();
    expect(within(dialog).getByText(/Please consult your doctor/)).toBeInTheDocument();
    expect(dialog).toHaveTextContent('Generated by the demo lab');
  });

  it('flags out-of-range values in the value column of a table', async () => {
    renderWithProviders(<DocumentDialog document={REPORT} onClose={vi.fn()} />);
    const table = await screen.findByRole('table');
    const headers = within(table)
      .getAllByRole('columnheader')
      .map((h) => h.textContent);
    expect(headers).toEqual(['Test', 'Value', 'Range']);
    const rows = within(table).getAllByRole('row').slice(1);
    expect(rows.map((r) => r.textContent)).toEqual([
      'Haemoglobin10.1 (L)12–16',
      'Glucose160 (H)70–110',
      'Sodium140135–145',
    ]);
  });

  it('leaves out the subtitle, footer and headings a document does not have', async () => {
    view.compact = true;
    const plain: DocumentAttachment = {
      ...REPORT,
      fileName: 'note.pdf',
      preview: { title: 'A note', sections: [{ kind: 'text', text: 'Just text.' }] },
    };
    renderWithProviders(<DocumentDialog document={plain} onClose={vi.fn()} />);
    const dialog = await screen.findByRole('dialog', { name: /note\.pdf/ });
    expect(within(dialog).queryByRole('heading', { level: 3 })).not.toBeInTheDocument();
    expect(dialog).not.toHaveTextContent('Patient: Asha Nair');
    expect(dialog).not.toHaveTextContent('Generated by the demo lab');
    expect(within(dialog).getByText('Just text.')).toBeInTheDocument();
  });

  it('closes from its close button', async () => {
    const onClose = vi.fn();
    renderWithProviders(<DocumentDialog document={REPORT} onClose={onClose} />);
    await userEvent.setup().click(await screen.findByRole('button', { name: 'Close' }));
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it('is closed without a document', () => {
    renderWithProviders(<DocumentDialog document={null} onClose={vi.fn()} />);
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  });
});
