import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { screen, within } from '@testing-library/react';
import type { ChatMessage } from '@exyconn/wa-flow';
import { MessageList } from '../../../../../src/components/wa/chat/MessageList';
import { renderWithProviders } from '../../../test-utils';
import { message } from '../wa-ui.fixtures';

const view = vi.hoisted(() => ({ reduced: false, compact: false }));

vi.mock('../../../../../src/theme/useWa', async (importOriginal) => ({
  ...(await importOriginal<object>()),
  useReducedMotion: () => view.reduced,
  useCompact: () => view.compact,
}));
vi.mock('../../../../../src/hooks/useWaFormat', () => ({
  useWaFormat: () => ({
    date: (ms: number) => `date:${ms}`,
    time: (ms: number) => `time:${ms}`,
    day: String,
    money: String,
  }),
}));
vi.mock('../../../../../src/components/wa/messages/MessageView', () => ({
  MessageView: (props: Readonly<{ message: ChatMessage; tail: boolean; time: string }>) => (
    <p>{`${props.message.id} tail=${String(props.tail)} ${props.time}`}</p>
  ),
}));

const NOW = new Date(2026, 9, 7, 12, 0);
const today = new Date(2026, 9, 7, 9, 30).getTime();
const yesterday = new Date(2026, 9, 6, 18, 0).getTime();
const older = new Date(2026, 9, 1, 8, 0).getTime();
const scrollTo = vi.fn();

beforeEach(() => {
  vi.useFakeTimers({ toFake: ['Date'] });
  vi.setSystemTime(NOW);
  Object.defineProperty(HTMLElement.prototype, 'scrollTo', {
    configurable: true,
    writable: true,
    value: scrollTo,
  });
});
afterEach(() => {
  vi.useRealTimers();
  view.reduced = false;
  view.compact = false;
  scrollTo.mockReset();
});

describe('MessageList', () => {
  it('opens with the notice that messages stay on the page', () => {
    renderWithProviders(<MessageList messages={[]} typing={false} />);
    expect(
      screen.getByText(
        'Messages in this demo are generated by an automation engine and stay on this page.',
      ),
    ).toBeInTheDocument();
    expect(screen.queryByRole('separator')).not.toBeInTheDocument();
  });

  it('separates days with Today, Yesterday or the formatted date', () => {
    renderWithProviders(
      <MessageList
        messages={[message('m1', older), message('m2', yesterday), message('m3', today)]}
        typing={false}
      />,
      { messages: { Today: "Aujourd'hui" } },
    );
    const log = screen.getByRole('log');
    const chips = within(log)
      .getAllByRole('separator')
      .map((s) => s.textContent);
    expect(chips).toEqual([`date:${new Date(2026, 9, 1).getTime()}`, 'Yesterday', "Aujourd'hui"]);
  });

  it('draws each message with its time and tail', () => {
    renderWithProviders(
      <MessageList
        messages={[
          message('b1', today),
          message('b2', today + 1000),
          message('u1', today + 2000, { type: 'text', text: 'hi' }, 'user'),
        ]}
        typing={false}
      />,
    );
    expect(screen.getByText(`b1 tail=true time:${today}`)).toBeInTheDocument();
    expect(screen.getByText(`b2 tail=false time:${today + 1000}`)).toBeInTheDocument();
    expect(screen.getByText(`u1 tail=true time:${today + 2000}`)).toBeInTheDocument();
  });

  it('keeps a wide gutter on a wide screen and a narrow one on a phone', () => {
    const { unmount } = renderWithProviders(<MessageList messages={[]} typing={false} />);
    expect(screen.getByRole('region', { name: 'Messages' })).toHaveStyle({ paddingLeft: '63px' });
    unmount();

    view.compact = true;
    renderWithProviders(<MessageList messages={[]} typing={false} />);
    expect(screen.getByRole('region', { name: 'Messages' })).toHaveStyle({ paddingLeft: '12px' });
  });

  it('shows the typing bubble while the business types', () => {
    renderWithProviders(<MessageList messages={[]} typing />);
    expect(screen.getByRole('status', { name: 'typing…' })).toBeInTheDocument();
  });

  it('scrolls smoothly to the newest message', () => {
    renderWithProviders(<MessageList messages={[message('m1', today)]} typing={false} />);
    expect(screen.getByRole('region', { name: 'Messages' })).toHaveAttribute('tabindex', '0');
    expect(scrollTo).toHaveBeenLastCalledWith({ top: 0, behavior: 'smooth' });
  });

  it('jumps without animation when the viewer asked for less motion', () => {
    view.reduced = true;
    renderWithProviders(<MessageList messages={[message('m1', today)]} typing={false} />);
    expect(scrollTo).toHaveBeenLastCalledWith({ top: 0, behavior: 'auto' });
  });

  it('scrolls again when a new message arrives', () => {
    const { rerender } = renderWithProviders(
      <MessageList messages={[message('m1', today)]} typing={false} />,
    );
    const calls = scrollTo.mock.calls.length;
    rerender(
      <MessageList messages={[message('m1', today), message('m2', today + 1)]} typing={false} />,
    );
    expect(scrollTo.mock.calls.length).toBe(calls + 1);
  });
});
