import {
  RolePermissionModel,
  type PermissionAction,
} from '../modules/permissions/permission.model';
import { assertRole } from '../middleware/roleGuard';
import { forbidden } from '../utils/errors';
import { ROLES, type Role } from '../constants/roles';
import type { GraphQLContext } from '../middleware/auth';

/**
 * Modules whose resolvers are hand-written rather than generated by
 * `createCrudResolvers`, which registers its own. Seeded here so the admin matrix
 * lists them without every resolver file needing a registration line of its own.
 */
const HAND_WRITTEN_MODULES = [
  'AppSettings',
  'AuditLog',
  'Branding',
  'Infrastructure',
  'SalarySlip',
  'TechConfig',
  'Tracker',
  'User',
  'WebsiteSubmission',
] as const;

/** Every module that registered a guard, so the admin matrix can list them. */
export const PERMISSION_MODULES = new Set<string>(HAND_WRITTEN_MODULES);

/** What one role may do inside one module, as the client reads it off `myPermissions`. */
export interface ModulePermission {
  module: string;
  view: boolean;
  create: boolean;
  edit: boolean;
  delete: boolean;
  approve: boolean;
  export: boolean;
}

const CACHE_TTL_MS = 10_000;
let cache: { at: number; rows: Map<string, Set<string>> } | null = null;

/** (role, module) -> allowed actions, refreshed at most every 10s. Undefined = no restriction. */
async function restrictions(): Promise<Map<string, Set<string>>> {
  if (cache && Date.now() - cache.at < CACHE_TTL_MS) return cache.rows;
  const rows = await RolePermissionModel.find().lean();
  const map = new Map(rows.map((r) => [`${r.role}:${r.module}`, new Set<string>(r.actions)]));
  cache = { at: Date.now(), rows: map };
  return map;
}

/** Call after any permission write so the next check sees it. */
export function invalidatePermissionCache(): void {
  cache = null;
}

/** Whether any of these roles leaves `action` open on `module`. A missing row allows it. */
function allows(
  map: Map<string, Set<string>>,
  roles: Role[],
  module: string,
  action: PermissionAction,
): boolean {
  return roles.some((role) => {
    const allowed = map.get(`${role}:${module}`);
    return allowed === undefined || allowed.has(action);
  });
}

/**
 * The module's base roles still gate entry (as before). On top of that, if an
 * administrator has restricted one of the caller's roles for this module, the
 * action must be in that role's allowed list. ADMIN is never restricted.
 */
export async function assertPermission(
  ctx: GraphQLContext,
  module: string,
  baseRoles: Role[],
  action: PermissionAction,
) {
  const user = assertRole(ctx, baseRoles);
  const roles = (user.roles ?? []) as Role[];
  if (roles.includes(ROLES.ADMIN)) return user;

  const map = await restrictions();
  const scoped = roles.filter((role) => baseRoles.includes(role));
  if (!allows(map, scoped, module, action)) {
    forbidden(`Your role may not ${action.toLowerCase()} ${module}`);
  }
  return user;
}

/**
 * The APPROVE half of a decision a manager may also make.
 *
 * A manager reaching an approval through their own reporting line (`assertMayActFor`)
 * is not acting through the module's role at all, so there is nothing for the matrix
 * to restrict — checking would lock them out of their own report's request. Only a
 * caller who holds one of the module's roles is measured against the matrix.
 */
export async function assertApprovePermission(
  ctx: GraphQLContext,
  module: string,
  baseRoles: Role[],
): Promise<void> {
  const roles = (ctx.user?.roles ?? []) as Role[];
  if (roles.includes(ROLES.ADMIN) || !roles.some((role) => baseRoles.includes(role))) {
    return;
  }
  await assertPermission(ctx, module, baseRoles, 'APPROVE');
}

/** Whether these roles may perform `action` on `module`, without throwing. */
export async function isAllowed(
  roles: Role[],
  module: string,
  action: PermissionAction,
): Promise<boolean> {
  if (roles.includes(ROLES.ADMIN)) return true;
  return allows(await restrictions(), roles, module, action);
}

/**
 * What these roles may do in every registered module — the matrix the client hides
 * buttons with, so a screen never offers an action the server would refuse.
 */
export async function permissionsFor(roles: Role[]): Promise<ModulePermission[]> {
  const isAdmin = roles.includes(ROLES.ADMIN);
  const map = await restrictions();
  const can = (module: string, action: PermissionAction) =>
    isAdmin || allows(map, roles, module, action);
  return [...PERMISSION_MODULES]
    .sort((a, b) => a.localeCompare(b))
    .map((module) => ({
      module,
      view: can(module, 'VIEW'),
      create: can(module, 'CREATE'),
      edit: can(module, 'EDIT'),
      delete: can(module, 'DELETE'),
      approve: can(module, 'APPROVE'),
      export: can(module, 'EXPORT'),
    }));
}
