/**
 * exyconn.com's design tokens exactly as the website's token plugin emits them
 * (exyconn-website/src/styles/tokens: semantic roles by day and by night, the type family,
 * radii, shadows and spacing), so the CSS variables the CMS writes equal today's and the
 * first render from the CMS is identical. Colour roles point at the palette ramps
 * (`var(--palette-…)`), which the website still defines; an editor may replace any value
 * with a literal colour.
 *
 * Generated from the website's token files when the CMS was introduced; edit the design
 * system in Website › Design System from then on.
 */
export const EXYCONN_TOKENS = {
  colors: {
    light: {
      page: 'var(--palette-base-white)',
      surface: 'var(--palette-base-white)',
      'surface-subtle': 'var(--palette-gray-50)',
      'surface-muted': 'var(--palette-gray-100)',
      'surface-strong': 'var(--palette-gray-200)',
      inverse: 'var(--palette-gray-900)',
      'inverse-muted': 'var(--palette-gray-800)',
      fg: 'var(--palette-gray-900)',
      'fg-secondary': 'var(--palette-gray-700)',
      'fg-muted': 'var(--palette-gray-600)',
      'fg-subtle': 'color-mix(in oklab, var(--palette-gray-500), var(--palette-gray-600))',
      'fg-faint': 'var(--color-fg-subtle)',
      'line-subtle': 'var(--palette-gray-100)',
      line: 'var(--palette-gray-200)',
      'line-strong': 'var(--palette-gray-300)',
      'on-solid': 'var(--palette-base-white)',
      'on-solid-muted': 'color-mix(in srgb, var(--palette-base-white) 75%, transparent)',
      'on-bright': 'var(--palette-gray-950)',
      scrim: 'var(--palette-base-black)',
      primary: 'var(--palette-brand-500)',
      'primary-hover': 'var(--palette-brand-600)',
      'on-primary': 'var(--palette-base-white)',
      'primary-faint': 'color-mix(in srgb, var(--palette-brand-500) 4%, transparent)',
      'primary-subtle': 'color-mix(in srgb, var(--palette-brand-500) 12.5%, transparent)',
      'primary-soft': 'color-mix(in srgb, var(--palette-brand-500) 25%, transparent)',
      'focus-ring': 'var(--palette-brand-500)',
      'field-bg': 'var(--palette-base-white)',
      'field-bg-focus': 'var(--palette-sky-50)',
      'field-ring': 'var(--color-primary-subtle)',
      'fg-placeholder': 'var(--color-fg-subtle)',
      'field-border': 'color-mix(in oklab, var(--palette-gray-400), var(--palette-gray-500))',
      'button-bg': 'var(--palette-brand-500)',
      'button-fg': 'var(--palette-base-white)',
      'surface-disabled': 'var(--palette-slate-300)',
      'fg-disabled': 'var(--palette-gray-500)',
      'red-subtle': 'var(--palette-red-50)',
      'red-soft': 'var(--palette-red-100)',
      'red-muted': 'var(--palette-red-200)',
      red: 'var(--palette-red-500)',
      'red-strong': 'var(--palette-red-600)',
      'red-deep': 'var(--palette-red-700)',
      'red-night': 'var(--palette-red-950)',
      'red-bright': 'var(--palette-red-400)',
      'red-fg': 'var(--palette-red-700)',
      'red-fg-strong': 'var(--palette-red-800)',
      'red-fg-deep': 'var(--palette-red-900)',
      'orange-subtle': 'var(--palette-orange-50)',
      'orange-soft': 'var(--palette-orange-100)',
      'orange-muted': 'var(--palette-orange-200)',
      orange: 'var(--palette-orange-500)',
      'orange-strong': 'var(--palette-orange-600)',
      'orange-deep': 'var(--palette-orange-700)',
      'orange-night': 'var(--palette-orange-950)',
      'orange-bright': 'var(--palette-orange-400)',
      'orange-fg': 'var(--palette-orange-700)',
      'orange-fg-strong': 'var(--palette-orange-800)',
      'orange-fg-deep': 'var(--palette-orange-900)',
      'amber-subtle': 'var(--palette-amber-50)',
      'amber-soft': 'var(--palette-amber-100)',
      'amber-muted': 'var(--palette-amber-200)',
      amber: 'var(--palette-amber-500)',
      'amber-strong': 'var(--palette-amber-600)',
      'amber-deep': 'var(--palette-amber-700)',
      'amber-night': 'var(--palette-amber-950)',
      'amber-bright': 'var(--palette-amber-400)',
      'amber-fg': 'var(--palette-amber-700)',
      'amber-fg-strong': 'var(--palette-amber-800)',
      'amber-fg-deep': 'var(--palette-amber-900)',
      'yellow-subtle': 'var(--palette-yellow-50)',
      'yellow-soft': 'var(--palette-yellow-100)',
      'yellow-muted': 'var(--palette-yellow-200)',
      yellow: 'var(--palette-yellow-500)',
      'yellow-strong': 'var(--palette-yellow-600)',
      'yellow-deep': 'var(--palette-yellow-700)',
      'yellow-night': 'var(--palette-yellow-950)',
      'yellow-bright': 'var(--palette-yellow-400)',
      'yellow-fg': 'var(--palette-yellow-800)',
      'yellow-fg-strong': 'var(--palette-yellow-900)',
      'yellow-fg-deep': 'var(--palette-yellow-900)',
      'lime-subtle': 'var(--palette-lime-50)',
      'lime-soft': 'var(--palette-lime-100)',
      'lime-muted': 'var(--palette-lime-200)',
      lime: 'var(--palette-lime-500)',
      'lime-strong': 'var(--palette-lime-600)',
      'lime-deep': 'var(--palette-lime-700)',
      'lime-night': 'var(--palette-lime-950)',
      'lime-bright': 'var(--palette-lime-400)',
      'lime-fg': 'var(--palette-lime-700)',
      'lime-fg-strong': 'var(--palette-lime-800)',
      'lime-fg-deep': 'var(--palette-lime-900)',
      'green-subtle': 'var(--palette-green-50)',
      'green-soft': 'var(--palette-green-100)',
      'green-muted': 'var(--palette-green-200)',
      green: 'var(--palette-green-500)',
      'green-strong': 'var(--palette-green-600)',
      'green-deep': 'var(--palette-green-700)',
      'green-night': 'var(--palette-green-950)',
      'green-bright': 'var(--palette-green-400)',
      'green-fg': 'var(--palette-green-800)',
      'green-fg-strong': 'var(--palette-green-900)',
      'green-fg-deep': 'var(--palette-green-900)',
      'emerald-subtle': 'var(--palette-emerald-50)',
      'emerald-soft': 'var(--palette-emerald-100)',
      'emerald-muted': 'var(--palette-emerald-200)',
      emerald: 'var(--palette-emerald-500)',
      'emerald-strong': 'var(--palette-emerald-600)',
      'emerald-deep': 'var(--palette-emerald-700)',
      'emerald-night': 'var(--palette-emerald-950)',
      'emerald-bright': 'var(--palette-emerald-400)',
      'emerald-fg': 'var(--palette-emerald-700)',
      'emerald-fg-strong': 'var(--palette-emerald-800)',
      'emerald-fg-deep': 'var(--palette-emerald-900)',
      'teal-subtle': 'var(--palette-teal-50)',
      'teal-soft': 'var(--palette-teal-100)',
      'teal-muted': 'var(--palette-teal-200)',
      teal: 'var(--palette-teal-500)',
      'teal-strong': 'var(--palette-teal-600)',
      'teal-deep': 'var(--palette-teal-700)',
      'teal-night': 'var(--palette-teal-950)',
      'teal-bright': 'var(--palette-teal-400)',
      'teal-fg': 'var(--palette-teal-700)',
      'teal-fg-strong': 'var(--palette-teal-800)',
      'teal-fg-deep': 'var(--palette-teal-900)',
      'cyan-subtle': 'var(--palette-cyan-50)',
      'cyan-soft': 'var(--palette-cyan-100)',
      'cyan-muted': 'var(--palette-cyan-200)',
      cyan: 'var(--palette-cyan-500)',
      'cyan-strong': 'var(--palette-cyan-600)',
      'cyan-deep': 'var(--palette-cyan-700)',
      'cyan-night': 'var(--palette-cyan-950)',
      'cyan-bright': 'var(--palette-cyan-400)',
      'cyan-fg': 'var(--palette-cyan-700)',
      'cyan-fg-strong': 'var(--palette-cyan-800)',
      'cyan-fg-deep': 'var(--palette-cyan-900)',
      'sky-subtle': 'var(--palette-sky-50)',
      'sky-soft': 'var(--palette-sky-100)',
      'sky-muted': 'var(--palette-sky-200)',
      sky: 'var(--palette-sky-500)',
      'sky-strong': 'var(--palette-sky-600)',
      'sky-deep': 'var(--palette-sky-700)',
      'sky-night': 'var(--palette-sky-950)',
      'sky-bright': 'var(--palette-sky-400)',
      'sky-fg': 'var(--palette-sky-700)',
      'sky-fg-strong': 'var(--palette-sky-800)',
      'sky-fg-deep': 'var(--palette-sky-900)',
      'blue-subtle': 'var(--palette-blue-50)',
      'blue-soft': 'var(--palette-blue-100)',
      'blue-muted': 'var(--palette-blue-200)',
      blue: 'var(--palette-blue-500)',
      'blue-strong': 'var(--palette-blue-600)',
      'blue-deep': 'var(--palette-blue-700)',
      'blue-night': 'var(--palette-blue-950)',
      'blue-bright': 'var(--palette-blue-400)',
      'blue-fg': 'var(--palette-blue-700)',
      'blue-fg-strong': 'var(--palette-blue-800)',
      'blue-fg-deep': 'var(--palette-blue-900)',
      'indigo-subtle': 'var(--palette-indigo-50)',
      'indigo-soft': 'var(--palette-indigo-100)',
      'indigo-muted': 'var(--palette-indigo-200)',
      indigo: 'var(--palette-indigo-500)',
      'indigo-strong': 'var(--palette-indigo-600)',
      'indigo-deep': 'var(--palette-indigo-700)',
      'indigo-night': 'var(--palette-indigo-950)',
      'indigo-bright': 'var(--palette-indigo-400)',
      'indigo-fg': 'var(--palette-indigo-700)',
      'indigo-fg-strong': 'var(--palette-indigo-800)',
      'indigo-fg-deep': 'var(--palette-indigo-900)',
      'violet-subtle': 'var(--palette-violet-50)',
      'violet-soft': 'var(--palette-violet-100)',
      'violet-muted': 'var(--palette-violet-200)',
      violet: 'var(--palette-violet-500)',
      'violet-strong': 'var(--palette-violet-600)',
      'violet-deep': 'var(--palette-violet-700)',
      'violet-night': 'var(--palette-violet-950)',
      'violet-bright': 'var(--palette-violet-400)',
      'violet-fg': 'var(--palette-violet-700)',
      'violet-fg-strong': 'var(--palette-violet-800)',
      'violet-fg-deep': 'var(--palette-violet-900)',
      'purple-subtle': 'var(--palette-purple-50)',
      'purple-soft': 'var(--palette-purple-100)',
      'purple-muted': 'var(--palette-purple-200)',
      purple: 'var(--palette-purple-500)',
      'purple-strong': 'var(--palette-purple-600)',
      'purple-deep': 'var(--palette-purple-700)',
      'purple-night': 'var(--palette-purple-950)',
      'purple-bright': 'var(--palette-purple-400)',
      'purple-fg': 'var(--palette-purple-700)',
      'purple-fg-strong': 'var(--palette-purple-800)',
      'purple-fg-deep': 'var(--palette-purple-900)',
      'fuchsia-subtle': 'var(--palette-fuchsia-50)',
      'fuchsia-soft': 'var(--palette-fuchsia-100)',
      'fuchsia-muted': 'var(--palette-fuchsia-200)',
      fuchsia: 'var(--palette-fuchsia-500)',
      'fuchsia-strong': 'var(--palette-fuchsia-600)',
      'fuchsia-deep': 'var(--palette-fuchsia-700)',
      'fuchsia-night': 'var(--palette-fuchsia-950)',
      'fuchsia-bright': 'var(--palette-fuchsia-400)',
      'fuchsia-fg': 'var(--palette-fuchsia-700)',
      'fuchsia-fg-strong': 'var(--palette-fuchsia-800)',
      'fuchsia-fg-deep': 'var(--palette-fuchsia-900)',
      'pink-subtle': 'var(--palette-pink-50)',
      'pink-soft': 'var(--palette-pink-100)',
      'pink-muted': 'var(--palette-pink-200)',
      pink: 'var(--palette-pink-500)',
      'pink-strong': 'var(--palette-pink-600)',
      'pink-deep': 'var(--palette-pink-700)',
      'pink-night': 'var(--palette-pink-950)',
      'pink-bright': 'var(--palette-pink-400)',
      'pink-fg': 'var(--palette-pink-700)',
      'pink-fg-strong': 'var(--palette-pink-800)',
      'pink-fg-deep': 'var(--palette-pink-900)',
      'rose-subtle': 'var(--palette-rose-50)',
      'rose-soft': 'var(--palette-rose-100)',
      'rose-muted': 'var(--palette-rose-200)',
      rose: 'var(--palette-rose-500)',
      'rose-strong': 'var(--palette-rose-600)',
      'rose-deep': 'var(--palette-rose-700)',
      'rose-night': 'var(--palette-rose-950)',
      'rose-bright': 'var(--palette-rose-400)',
      'rose-fg': 'var(--palette-rose-700)',
      'rose-fg-strong': 'var(--palette-rose-800)',
      'rose-fg-deep': 'var(--palette-rose-900)',
    },
    dark: {
      page: 'var(--palette-ink-900)',
      surface: 'var(--palette-ink-800)',
      'surface-subtle': 'var(--palette-ink-900)',
      'surface-muted': 'var(--palette-ink-700)',
      'surface-strong': 'var(--palette-ink-600)',
      inverse: 'var(--palette-ink-950)',
      'inverse-muted': 'var(--palette-ink-800)',
      fg: 'var(--palette-gray-50)',
      'fg-secondary': 'var(--palette-gray-200)',
      'fg-muted': 'var(--palette-gray-300)',
      'fg-subtle': 'var(--palette-gray-400)',
      'line-subtle': 'var(--palette-ink-700)',
      line: 'var(--palette-ink-600)',
      'line-strong': 'var(--palette-gray-600)',
      primary: 'var(--palette-brand-300)',
      'primary-hover': 'var(--palette-sky-300)',
      'on-primary': 'var(--palette-ink-900)',
      'focus-ring': 'var(--palette-brand-300)',
      'field-bg': 'var(--palette-ink-800)',
      'field-bg-focus': 'var(--palette-ink-700)',
      'field-ring': 'var(--color-primary-soft)',
      'button-bg': 'var(--palette-ink-700)',
      'button-fg': 'var(--palette-gray-100)',
      'surface-disabled': 'var(--palette-gray-700)',
      'red-subtle': 'color-mix(in oklab, var(--palette-red-500) 10%, var(--palette-ink-900))',
      'red-soft': 'color-mix(in oklab, var(--palette-red-500) 18%, var(--palette-ink-900))',
      'red-muted': 'color-mix(in oklab, var(--palette-red-500) 30%, var(--palette-ink-900))',
      'red-fg': 'var(--palette-red-400)',
      'red-fg-strong': 'var(--palette-red-300)',
      'red-fg-deep': 'var(--palette-red-200)',
      'orange-subtle': 'color-mix(in oklab, var(--palette-orange-500) 10%, var(--palette-ink-900))',
      'orange-soft': 'color-mix(in oklab, var(--palette-orange-500) 18%, var(--palette-ink-900))',
      'orange-muted': 'color-mix(in oklab, var(--palette-orange-500) 30%, var(--palette-ink-900))',
      'orange-fg': 'var(--palette-orange-400)',
      'orange-fg-strong': 'var(--palette-orange-300)',
      'orange-fg-deep': 'var(--palette-orange-200)',
      'amber-subtle': 'color-mix(in oklab, var(--palette-amber-500) 10%, var(--palette-ink-900))',
      'amber-soft': 'color-mix(in oklab, var(--palette-amber-500) 18%, var(--palette-ink-900))',
      'amber-muted': 'color-mix(in oklab, var(--palette-amber-500) 30%, var(--palette-ink-900))',
      'amber-fg': 'var(--palette-amber-400)',
      'amber-fg-strong': 'var(--palette-amber-300)',
      'amber-fg-deep': 'var(--palette-amber-200)',
      'yellow-subtle': 'color-mix(in oklab, var(--palette-yellow-500) 10%, var(--palette-ink-900))',
      'yellow-soft': 'color-mix(in oklab, var(--palette-yellow-500) 18%, var(--palette-ink-900))',
      'yellow-muted': 'color-mix(in oklab, var(--palette-yellow-500) 30%, var(--palette-ink-900))',
      'yellow-fg': 'var(--palette-yellow-400)',
      'yellow-fg-strong': 'var(--palette-yellow-300)',
      'yellow-fg-deep': 'var(--palette-yellow-200)',
      'lime-subtle': 'color-mix(in oklab, var(--palette-lime-500) 10%, var(--palette-ink-900))',
      'lime-soft': 'color-mix(in oklab, var(--palette-lime-500) 18%, var(--palette-ink-900))',
      'lime-muted': 'color-mix(in oklab, var(--palette-lime-500) 30%, var(--palette-ink-900))',
      'lime-fg': 'var(--palette-lime-400)',
      'lime-fg-strong': 'var(--palette-lime-300)',
      'lime-fg-deep': 'var(--palette-lime-200)',
      'green-subtle': 'color-mix(in oklab, var(--palette-green-500) 10%, var(--palette-ink-900))',
      'green-soft': 'color-mix(in oklab, var(--palette-green-500) 18%, var(--palette-ink-900))',
      'green-muted': 'color-mix(in oklab, var(--palette-green-500) 30%, var(--palette-ink-900))',
      'green-fg': 'var(--palette-green-400)',
      'green-fg-strong': 'var(--palette-green-300)',
      'green-fg-deep': 'var(--palette-green-200)',
      'emerald-subtle':
        'color-mix(in oklab, var(--palette-emerald-500) 10%, var(--palette-ink-900))',
      'emerald-soft': 'color-mix(in oklab, var(--palette-emerald-500) 18%, var(--palette-ink-900))',
      'emerald-muted':
        'color-mix(in oklab, var(--palette-emerald-500) 30%, var(--palette-ink-900))',
      'emerald-fg': 'var(--palette-emerald-400)',
      'emerald-fg-strong': 'var(--palette-emerald-300)',
      'emerald-fg-deep': 'var(--palette-emerald-200)',
      'teal-subtle': 'color-mix(in oklab, var(--palette-teal-500) 10%, var(--palette-ink-900))',
      'teal-soft': 'color-mix(in oklab, var(--palette-teal-500) 18%, var(--palette-ink-900))',
      'teal-muted': 'color-mix(in oklab, var(--palette-teal-500) 30%, var(--palette-ink-900))',
      'teal-fg': 'var(--palette-teal-400)',
      'teal-fg-strong': 'var(--palette-teal-300)',
      'teal-fg-deep': 'var(--palette-teal-200)',
      'cyan-subtle': 'color-mix(in oklab, var(--palette-cyan-500) 10%, var(--palette-ink-900))',
      'cyan-soft': 'color-mix(in oklab, var(--palette-cyan-500) 18%, var(--palette-ink-900))',
      'cyan-muted': 'color-mix(in oklab, var(--palette-cyan-500) 30%, var(--palette-ink-900))',
      'cyan-fg': 'var(--palette-cyan-400)',
      'cyan-fg-strong': 'var(--palette-cyan-300)',
      'cyan-fg-deep': 'var(--palette-cyan-200)',
      'sky-subtle': 'color-mix(in oklab, var(--palette-sky-500) 10%, var(--palette-ink-900))',
      'sky-soft': 'color-mix(in oklab, var(--palette-sky-500) 18%, var(--palette-ink-900))',
      'sky-muted': 'color-mix(in oklab, var(--palette-sky-500) 30%, var(--palette-ink-900))',
      'sky-fg': 'var(--palette-sky-400)',
      'sky-fg-strong': 'var(--palette-sky-300)',
      'sky-fg-deep': 'var(--palette-sky-200)',
      'blue-subtle': 'color-mix(in oklab, var(--palette-blue-500) 10%, var(--palette-ink-900))',
      'blue-soft': 'color-mix(in oklab, var(--palette-blue-500) 18%, var(--palette-ink-900))',
      'blue-muted': 'color-mix(in oklab, var(--palette-blue-500) 30%, var(--palette-ink-900))',
      'blue-fg': 'var(--palette-blue-400)',
      'blue-fg-strong': 'var(--palette-blue-300)',
      'blue-fg-deep': 'var(--palette-blue-200)',
      'indigo-subtle': 'color-mix(in oklab, var(--palette-indigo-500) 10%, var(--palette-ink-900))',
      'indigo-soft': 'color-mix(in oklab, var(--palette-indigo-500) 18%, var(--palette-ink-900))',
      'indigo-muted': 'color-mix(in oklab, var(--palette-indigo-500) 30%, var(--palette-ink-900))',
      'indigo-fg': 'var(--palette-indigo-400)',
      'indigo-fg-strong': 'var(--palette-indigo-300)',
      'indigo-fg-deep': 'var(--palette-indigo-200)',
      'violet-subtle': 'color-mix(in oklab, var(--palette-violet-500) 10%, var(--palette-ink-900))',
      'violet-soft': 'color-mix(in oklab, var(--palette-violet-500) 18%, var(--palette-ink-900))',
      'violet-muted': 'color-mix(in oklab, var(--palette-violet-500) 30%, var(--palette-ink-900))',
      'violet-fg': 'var(--palette-violet-400)',
      'violet-fg-strong': 'var(--palette-violet-300)',
      'violet-fg-deep': 'var(--palette-violet-200)',
      'purple-subtle': 'color-mix(in oklab, var(--palette-purple-500) 10%, var(--palette-ink-900))',
      'purple-soft': 'color-mix(in oklab, var(--palette-purple-500) 18%, var(--palette-ink-900))',
      'purple-muted': 'color-mix(in oklab, var(--palette-purple-500) 30%, var(--palette-ink-900))',
      'purple-fg': 'var(--palette-purple-400)',
      'purple-fg-strong': 'var(--palette-purple-300)',
      'purple-fg-deep': 'var(--palette-purple-200)',
      'fuchsia-subtle':
        'color-mix(in oklab, var(--palette-fuchsia-500) 10%, var(--palette-ink-900))',
      'fuchsia-soft': 'color-mix(in oklab, var(--palette-fuchsia-500) 18%, var(--palette-ink-900))',
      'fuchsia-muted':
        'color-mix(in oklab, var(--palette-fuchsia-500) 30%, var(--palette-ink-900))',
      'fuchsia-fg': 'var(--palette-fuchsia-400)',
      'fuchsia-fg-strong': 'var(--palette-fuchsia-300)',
      'fuchsia-fg-deep': 'var(--palette-fuchsia-200)',
      'pink-subtle': 'color-mix(in oklab, var(--palette-pink-500) 10%, var(--palette-ink-900))',
      'pink-soft': 'color-mix(in oklab, var(--palette-pink-500) 18%, var(--palette-ink-900))',
      'pink-muted': 'color-mix(in oklab, var(--palette-pink-500) 30%, var(--palette-ink-900))',
      'pink-fg': 'var(--palette-pink-400)',
      'pink-fg-strong': 'var(--palette-pink-300)',
      'pink-fg-deep': 'var(--palette-pink-200)',
      'rose-subtle': 'color-mix(in oklab, var(--palette-rose-500) 10%, var(--palette-ink-900))',
      'rose-soft': 'color-mix(in oklab, var(--palette-rose-500) 18%, var(--palette-ink-900))',
      'rose-muted': 'color-mix(in oklab, var(--palette-rose-500) 30%, var(--palette-ink-900))',
      'rose-fg': 'var(--palette-rose-400)',
      'rose-fg-strong': 'var(--palette-rose-300)',
      'rose-fg-deep': 'var(--palette-rose-200)',
    },
  },
  fonts: {
    sans: '"Inter Tight", sans-serif',
  },
  radii: {
    xs: '2px',
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    '2xl': '20px',
    '3xl': '24px',
    pill: '9999px',
    circle: '50%',
  },
  shadows: {
    none: 'none',
    xs: '0 1px 3px color-mix(in srgb, var(--palette-base-black) 6%, transparent)',
    sm: '0 2px 8px color-mix(in srgb, var(--palette-base-black) 6%, transparent)',
    md: '0 4px 16px color-mix(in srgb, var(--palette-base-black) 8%, transparent)',
    lg: '0 8px 32px color-mix(in srgb, var(--palette-base-black) 10%, transparent)',
    xl: '0 12px 48px color-mix(in srgb, var(--palette-base-black) 12%, transparent)',
    inset: 'inset 0 1px 2px color-mix(in srgb, var(--palette-base-black) 10%, transparent)',
  },
  spacing: {
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '8': '2rem',
    '10': '2.5rem',
    '12': '3rem',
    '16': '4rem',
    '24': '6rem',
  },
};

/**
 * The high-contrast answers (semantic.tokens.ts highContrastRoles). The design system's roles
 * are unlayered, so they would win over the plugin's high-contrast block; repeating it here,
 * after them, keeps a high-contrast visitor's colours as they were.
 */
export const EXYCONN_EXTRA_CSS =
  '@media (prefers-contrast: high){:root:not([data-theme="dark"]){--color-primary:var(--palette-brand-600);--color-fg-muted:var(--palette-gray-700);}}';
