/**
 * Every English word the widget shows, in one object so it can be translated in one place.
 * The bot name, welcome and offline messages and the FAQs come from the server's config.
 */
export const strings = {
  defaultTitle: 'Exyconn',
  openChat: 'Open chat',
  closeChat: 'Close chat',
  unread: (count: number) => (count === 1 ? '1 unread message' : `${count} unread messages`),
  online: 'Online',
  offline: 'Offline',
  settings: 'Chat settings',
  minimise: 'Minimise chat',
  sound: 'Sound',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  download: 'Download conversation',
  endChat: 'End chat',
  endConfirm: 'End this chat? A copy of the conversation is emailed to you.',
  endConfirmYes: 'Yes, end chat',
  cancel: 'Cancel',
  tabsLabel: 'Chat sections',
  tabLive: 'Chat with us',
  tabKnowledge: 'Knowledge Bot',
  tabFaqs: 'FAQs',
  connecting: 'Connecting…',
  reconnecting: 'Reconnecting…',
  notConnected: 'Not connected yet. Try again in a moment.',
  dismiss: 'Dismiss',
  signInTitle: 'Before we start',
  signInIntro: 'We email you a code to confirm it is you, and a copy of the chat when it ends.',
  name: 'Name',
  email: 'Email',
  phone: 'Phone (optional)',
  requestCode: 'Email me a code',
  privacy: 'How we use your details',
  nameRequired: 'Enter your name.',
  nameTooLong: 'Keep your name shorter.',
  nameLink: 'Enter your name without links or email addresses.',
  emailInvalid: 'Enter a valid email address.',
  phoneInvalid: 'Enter a valid phone number.',
  codeTitle: 'Check your email',
  codeSentTo: (email: string) => `We emailed a code to ${email}.`,
  code: '6-digit code',
  codeInvalid: 'Enter the 6-digit code from the email.',
  verify: 'Verify',
  resend: 'Resend code',
  resendIn: (seconds: number) => `Resend code in ${seconds}s`,
  changeEmail: 'Change email',
  welcomeKnowledge:
    'Hi! I am the Exyconn Knowledge Bot. Ask me about Exyconn — our services, products and how we work. I answer questions about Exyconn only.',
  switchNotice:
    'No one on the team could answer just now, so the Knowledge Bot has picked up your question here.',
  conversation: 'Conversation',
  messageLabel: 'Message',
  placeholder: 'Write a message…',
  send: 'Send message',
  charsLeft: (count: number) => `${count} characters left`,
  attach: 'Attach a picture or video',
  removeFile: (name: string) => `Remove ${name}`,
  fileTooBig: (name: string, mb: number) => `${name} is larger than ${mb} MB.`,
  tooManyFiles: 'Send at most four files at a time.',
  fileType: (name: string) => `${name} is not a picture or a video.`,
  fileUnreadable: 'The file could not be read.',
  record: 'Record a voice note',
  recording: 'Recording',
  stopSend: 'Stop and send',
  cancelRecording: 'Cancel recording',
  micDenied:
    'Microphone access is blocked. Allow it in your browser settings to send a voice note.',
  micFailed: 'The voice note could not be recorded.',
  voiceNote: 'Voice note',
  sending: 'Sending…',
  failed: 'Not sent',
  retry: 'Retry',
  seen: 'Seen',
  typing: (name: string) => `${name} is typing`,
  ended: 'This chat has ended.',
  newChat: 'Start a new chat',
  searchFaqs: 'Search FAQs',
  noFaqMatch: 'No answers match your search.',
  noFaqs: 'No FAQs yet.',
  stillNeedHelp: 'Still need help?',
  chatWithUs: 'Chat with us',
  newMessageFrom: (name: string, body: string) => `New message from ${name}: ${body}`,
  transcriptTitle: (reference: string) => `Exyconn chat ${reference}`,
  you: 'You',
} as const;
