import PDFDocument from 'pdfkit';
import { payslipLines, type PayslipLine } from './payslip.lines';
import type { StructureParts } from './payroll.compute';

/** Everything one payslip prints, already resolved from the database. */
export interface PayslipData {
  company: { name: string; address: string; supportEmail: string };
  employee: {
    name: string;
    email: string;
    designation: string;
    department: string;
    joinDate: Date | null;
  };
  slip: {
    month: number;
    year: number;
    currency: string;
    gross: number;
    deductions: number;
    net: number;
    status: string;
    issuedDate: Date;
  };
  structure: StructureParts | null;
}

const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

/** `August 2026` — the period a payslip covers, as it is printed and emailed. */
export function periodLabel(month: number, year: number): string {
  return `${MONTHS[month - 1]} ${year}`;
}

/** Money as the employee's own currency, e.g. `₹ 82,500.00`. */
export function formatAmount(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency }).format(amount);
}

const PAGE_MARGIN = 48;
const COLUMN_RIGHT = 400;
const INK = '#0f172a';
const MUTED = '#64748b';

/** Company block and the period this payslip covers. */
function drawHeader(doc: PDFKit.PDFDocument, data: PayslipData): void {
  doc.fillColor(INK).fontSize(18).text(data.company.name, { continued: false });
  doc.fillColor(MUTED).fontSize(9);
  if (data.company.address) {
    doc.text(data.company.address);
  }
  if (data.company.supportEmail) {
    doc.text(data.company.supportEmail);
  }
  doc.moveDown(1);
  doc
    .fillColor(INK)
    .fontSize(13)
    .text(`Payslip for ${periodLabel(data.slip.month, data.slip.year)}`);
  doc.moveDown(0.8);
}

/** One label/value line in the employee block. */
function drawField(doc: PDFKit.PDFDocument, label: string, value: string): void {
  doc.fillColor(MUTED).fontSize(9).text(label, { continued: true });
  doc.fillColor(INK).text(`  ${value}`);
}

function drawEmployee(doc: PDFKit.PDFDocument, data: PayslipData): void {
  const { employee, slip } = data;
  drawField(doc, 'Employee', employee.name);
  drawField(doc, 'Email', employee.email);
  if (employee.designation) {
    drawField(doc, 'Designation', employee.designation);
  }
  if (employee.department) {
    drawField(doc, 'Department', employee.department);
  }
  if (employee.joinDate) {
    drawField(doc, 'Joined', employee.joinDate.toISOString().slice(0, 10));
  }
  drawField(doc, 'Payment status', slip.status);
  drawField(doc, 'Issued', slip.issuedDate.toISOString().slice(0, 10));
  doc.moveDown(1);
}

/** A titled block of amount rows with its own total. */
function drawSection(
  doc: PDFKit.PDFDocument,
  title: string,
  lines: PayslipLine[],
  currency: string,
): void {
  doc.fillColor(INK).fontSize(11).text(title);
  doc.moveDown(0.3);
  doc.fontSize(10);
  for (const line of lines) {
    const top = doc.y;
    doc.fillColor(MUTED).text(line.label, PAGE_MARGIN, top);
    doc.fillColor(INK).text(formatAmount(line.amount, currency), COLUMN_RIGHT, top, {
      align: 'right',
      width: doc.page.width - COLUMN_RIGHT - PAGE_MARGIN,
    });
  }
  doc.moveDown(0.8);
}

/** The net figure, set apart because it is the number the employee came for. */
function drawNet(doc: PDFKit.PDFDocument, data: PayslipData): void {
  const top = doc.y;
  doc.fillColor(INK).fontSize(12).text('Net pay', PAGE_MARGIN, top);
  doc.fontSize(12).text(formatAmount(data.slip.net, data.slip.currency), COLUMN_RIGHT, top, {
    align: 'right',
    width: doc.page.width - COLUMN_RIGHT - PAGE_MARGIN,
  });
  doc.moveDown(1.5);
  doc
    .fillColor(MUTED)
    .fontSize(8)
    .text('This payslip is generated by the Exyconn portal and needs no signature.', {
      align: 'center',
    });
}

/**
 * Renders one payslip as a PDF. The same document is what the employee downloads, what
 * HR downloads and what the scheduled email attaches — one renderer, so the three can
 * never disagree about what an employee was paid.
 */
export function buildPayslipPdf(data: PayslipData): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN });
  const chunks: Buffer[] = [];
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  const { earnings, deductions } = payslipLines(data.slip, data.structure);
  drawHeader(doc, data);
  drawEmployee(doc, data);
  drawSection(doc, 'Earnings', earnings, data.slip.currency);
  drawSection(doc, 'Deductions', deductions, data.slip.currency);
  drawNet(doc, data);
  doc.end();

  return done;
}
