import {
  AuditKind,
  AuditStatus,
  ComplianceCategory,
  FindingSource,
  FindingStatus,
  FindingType,
  ManagementReviewStatus,
  ManagementStandard,
  ObjectiveFrequency,
  ObjectiveScope,
  ObjectiveStatus,
  RiskLevel,
  RiskStatus,
  RiskTreatment,
  type FindingFieldsFragment,
  type InternalAuditFieldsFragment,
  type ManagementReviewFieldsFragment,
  type ObjectiveFieldsFragment,
  type RiskFieldsFragment,
} from '@exyconn/shell/graphql/generated';

/** One row of each compliance register, valid as it stands, as the server returns it. */

export const riskRow = (over: Partial<RiskFieldsFragment> = {}): RiskFieldsFragment => ({
  id: 'risk-1',
  reference: 'RISK-0001',
  title: 'Laptop theft',
  description: 'A laptop is stolen from a car',
  standards: [ManagementStandard.Iso_27001],
  category: ComplianceCategory.InformationSecurity,
  subject: 'Endpoints',
  ownerId: 'user-1',
  ownerName: 'Asha',
  likelihood: 4,
  impact: 5,
  inherentScore: 20,
  inherentLevel: RiskLevel.Critical,
  treatment: RiskTreatment.Transfer,
  controls: 'Disk encryption',
  residualLikelihood: 1,
  residualImpact: 3,
  residualScore: 3,
  residualLevel: RiskLevel.Low,
  status: RiskStatus.Treating,
  identifiedOn: '2026-09-01T00:00:00.000Z',
  reviewDueOn: '2026-12-01T00:00:00.000Z',
  closedOn: null,
  ...over,
});

export const objectiveRow = (
  over: Partial<ObjectiveFieldsFragment> = {},
): ObjectiveFieldsFragment => ({
  id: 'objective-1',
  title: 'Fewer complaints',
  description: 'Halve the complaint rate',
  standards: [ManagementStandard.Iso_9001],
  category: ComplianceCategory.Quality,
  scope: ObjectiveScope.Department,
  area: 'Support',
  ownerId: 'user-2',
  ownerName: 'Ravi',
  measure: 'Complaints per 1,000 orders',
  unit: 'per 1k',
  baseline: 20,
  target: 10,
  actual: 15,
  achievementPercent: 50,
  frequency: ObjectiveFrequency.Monthly,
  periodStart: '2026-01-01T00:00:00.000Z',
  periodEnd: '2026-12-31T00:00:00.000Z',
  status: ObjectiveStatus.OnTrack,
  plan: 'Train the support team',
  ...over,
});

export const auditRow = (
  over: Partial<InternalAuditFieldsFragment> = {},
): InternalAuditFieldsFragment => ({
  id: 'audit-1',
  reference: 'AUD-0001',
  title: 'Access control audit',
  kind: AuditKind.Internal,
  standards: [ManagementStandard.Iso_27001, ManagementStandard.Iso_9001],
  scope: 'IT department',
  criteria: 'Annex A.5',
  leadAuditorId: 'user-3',
  leadAuditorName: 'Meera',
  auditeeName: 'IT',
  plannedOn: '2026-10-01T00:00:00.000Z',
  performedOn: '2026-10-05T00:00:00.000Z',
  status: AuditStatus.Reported,
  summary: 'Leaver accounts',
  conclusion: 'Effective with one minor finding',
  ...over,
});

export const findingRow = (over: Partial<FindingFieldsFragment> = {}): FindingFieldsFragment => ({
  id: 'finding-1',
  reference: 'FND-0001',
  title: 'Leaver account still active',
  description: 'Found during the access audit',
  source: FindingSource.InternalAudit,
  auditId: 'audit-1',
  riskId: 'risk-1',
  standards: [ManagementStandard.Iso_27001],
  category: ComplianceCategory.InformationSecurity,
  clause: '27001:A.5.18',
  type: FindingType.MajorNonconformity,
  immediateAction: 'Account disabled',
  rootCause: 'No leaver checklist',
  correctiveAction: 'Add a leaver checklist',
  ownerId: 'user-4',
  ownerName: 'Kiran',
  raisedOn: '2026-10-05T00:00:00.000Z',
  dueOn: '2026-11-05T00:00:00.000Z',
  status: FindingStatus.Verified,
  verifiedOn: '2026-11-10T00:00:00.000Z',
  verifiedByName: 'Meera',
  effective: true,
  effectivenessNote: 'No leaver left active since',
  closedOn: null,
  evidence: [
    {
      url: 'https://cdn.example.com/checklist.pdf',
      name: 'checklist.pdf',
      contentType: 'application/pdf',
      uploadedBy: 'user-4',
      uploadedAt: '2026-11-01T00:00:00.000Z',
    },
  ],
  ...over,
});

export const reviewRow = (
  over: Partial<ManagementReviewFieldsFragment> = {},
): ManagementReviewFieldsFragment => ({
  id: 'review-1',
  reference: 'MR-0001',
  title: 'Q3 management review',
  standards: [ManagementStandard.Iso_9001],
  heldOn: '2026-09-30T00:00:00.000Z',
  chairName: 'Priya',
  attendees: 'Leadership team',
  inputs: 'Audit results',
  decisions: 'The system is effective',
  openActionCount: 1,
  status: ManagementReviewStatus.Held,
  actions: [
    {
      description: 'Hire a second auditor',
      ownerName: 'Priya',
      dueOn: '2026-12-31T00:00:00.000Z',
      done: false,
    },
    { description: 'Refresh the policy', ownerName: '', dueOn: null, done: true },
  ],
  ...over,
});
