import { describe, expect, it } from 'vitest';
import * as ui from '../../src';

/**
 * Every name a consumer may import. A primitive dropped from the barrel by accident
 * would only surface as a type error in some app's build — catch it here instead.
 */
const EXPECTED = [
  // branded
  'Button',
  'IconButton',
  'AppBar',
  'Drawer',
  'TextField',
  // pass-through
  'Box',
  'Stack',
  'Grid',
  'Grid2',
  'Paper',
  'Typography',
  'Link',
  'Divider',
  'Chip',
  'Avatar',
  'Badge',
  'Tooltip',
  'Toolbar',
  'List',
  'ListItem',
  'ListItemButton',
  'ListItemIcon',
  'ListItemText',
  'Menu',
  'MenuItem',
  'Popover',
  'Alert',
  'Snackbar',
  'CircularProgress',
  'LinearProgress',
  'Skeleton',
  'Collapse',
  'Backdrop',
  'Autocomplete',
  'Tabs',
  'Tab',
  'Dialog',
  'DialogTitle',
  'DialogContent',
  'DialogActions',
  'Table',
  'TableBody',
  'TableCell',
  'TableContainer',
  'TableHead',
  'TableRow',
  'TablePagination',
  'Pagination',
  'Slider',
  'ToggleButton',
  'ToggleButtonGroup',
  'ButtonGroup',
  'Stepper',
  'Step',
  'StepLabel',
  'FormControlLabel',
  'FormHelperText',
  'FormControl',
  'InputLabel',
  'useMediaQuery',
  // pickers
  'LocalizationProvider',
  'AdapterDateFns',
  'DatePicker',
  'DateTimePicker',
  'TimePicker',
  'DateCalendar',
  'PickersDay',
  // styles + theme
  'styled',
  'alpha',
  'useTheme',
  'createTheme',
  'CssBaseline',
  'createAppTheme',
  'theme',
  // design-system groups
  'ThemeProvider',
  'spacing',
  'radius',
  'Heading',
  'Text',
  'Paragraph',
  'space',
  'Spacer',
  'Container',
  'Flex',
  'Section',
  'Checkbox',
  'Switch',
  'Radio',
  'RadioGroup',
  'Select',
  'Card',
  'CardHeader',
  'CardFooter',
] as const;

describe('@exyconn/ui barrel', () => {
  it.each(EXPECTED)('exports %s', (name) => {
    expect(ui[name as keyof typeof ui]).toBeDefined();
  });
});
